---
  - name: Install elasticsearch repository-s3 plugin
    elasticsearch_plugin:
      name: repository-s3
      state: present
      force: yes

  - name: Copy elk scripts
    copy:
      src: files/elk/
      dest: /usr/local/bin/
      mode: '0777'

  - name: Add cron job for backup index
    cron:
      name: "backup index"
      user: "ubuntu"
      minute: "10"
      hour: "3"
      job: "/opt/elk/backup-index-s3.sh"

  - name: Add cron job to remove last index
    cron:
      name: "remove old index"
      user: "ubuntu"
      minute: "20"
      hour: "3"
      job: "/opt/elk/delele-index.sh"

  - name: Copy elk environment
    template:
      src: files/env/.elk.example
      dest: /usr/local/bin/.elk

