#!/bin/bash

# Add to cron
# 0 1 * * * /usr/local/bin/backup-elk

if [ -z $1 ] 
then
  TODAY=$(date +'%Y.%m.%d')
  YESTERDAY=$(date --date="1 days ago" +'%Y.%m.%d')
  echo Today is $TODAY
  echo Yesterday $YESTERDAY indices will be stored in S3
else
  YESTERDAY=$1
fi

DIR_ELK=$(dirname $(readlink -f $0))
source ${DIR_ELK}/.elk

for prefix in $INDEX_PREFIXES;
do
  INDEX_NAME=${prefix}$YESTERDAY
  SNAPSHOT_NAME=${INDEX_NAME}"-snapshot"
  echo "Backup Snapshot ${INDEX_NAME}"
  curl -u "$ESU:$ESP" -H 'Content-Type: application/json' -XPUT "http://${DOMAIN}/_snapshot/${REPO}/${SNAPSHOT_NAME}?wait_for_completion=true" -d '{
    "indices": "'"${INDEX_NAME}"'",
    "ignore_unavailable": "true",
    "include_global_state": false
  }'
  echo "Successfully completed storing ${INDEX_NAME} in s3://${REPO}"
done