#!/bin/bash

DIR_ELK=$(dirname $(readlink -f $0))
source ${DIR_ELK}/.elk

echo "$ES_USR" | bin/elasticsearch-keystore add s3.client.default.access_key
echo "$ES_PASSWD" | bin/elasticsearch-keystore add s3.client.default.secret_key
service elasticsearch restart

JSON=$(cat <<EOL
{
  "type": "s3",
  "settings": {
    "bucket": "$REPO",
    "region": "$REGION",
    "base_path": "elasticsearch",
    "max_retries": 3
  }
}
EOL
)

curl -u "$ESU:$ESP" -H 'Content-Type: application/json' -XPUT "http://${DOMAIN}/_snapshot/${REPO}/" -d "$JSON"
